/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.app;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.Charset;
import java.util.List;

public class App {


    public static void main1(String[] args) throws Exception {
        List<String> targetFeedsList = List.of(
//                "https://cloudblog.withgoogle.com/rss/",
//                "https://eng.uber.com/feed/",
//                "https://eng.lyft.com/feed",
                "https://netflixtechblog.com/feed",
                "https://www.youtube.com/feeds/videos.xml?channel_id=UChr1x_GdwoNkduX5956VyGA");

//        for(String url : targetFeedsList){
//            List<NewsArticle> results = RSSReaderUtil.read(url);
//            System.out.println("url : "+url);
//            results.stream().forEach(a-> System.out.println(a.toString()));
//            System.out.println("==========");
//        }


        RssParser parser1 = new RssParser("https://www.youtube.com/feeds/videos.xml?channel_id=UChr1x_GdwoNkduX5956VyGA", "comrakof");
        parser1.read();
        RssParser parser2 = new RssParser("https://netflixtechblog.com/feed", "netflix");
        parser2.read();

        System.out.println("Default: " + Charset.defaultCharset());
    }
}
